---
language: python

services:
  - docker

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest tests

before_install:
  - pip install sphinx>=1.6.3
  - pip install pytest
  # - pip install mock
  - python setup.py install

deploy:
  provider: script
  script: bash docker/docker_push.sh
  on:
    branch: master
